"""empty message

Revision ID: 015953145b5c
Revises: 4d402df66673
Create Date: 2024-04-25 02:29:42.634641

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015953145b5c'
down_revision = '4d402df66673'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ban_tag',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tag.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ban_tag')
    # ### end Alembic commands ###
