"""empty message

Revision ID: 4d402df66673
Revises: 98282acab30a
Create Date: 2024-04-24 14:48:26.371171

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4d402df66673'
down_revision = '98282acab30a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('news_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'news', ['news_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('news_id')

    # ### end Alembic commands ###
