"""empty message

Revision ID: 67193aa49ba9
Revises: abf4b0df92e7
Create Date: 2024-04-26 12:10:46.219379

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67193aa49ba9'
down_revision = 'abf4b0df92e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('liked',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('news_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['news_id'], ['news.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('news_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_like', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('number_like')

    with op.batch_alter_table('blocks', schema=None) as batch_op:
        batch_op.alter_column('news_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.drop_table('liked')
    # ### end Alembic commands ###
